spring:
  port: 8080

web-client:
  max-connections: 100
  acquire-max-count: 100
  acquire-timeout: 10

external:
  service:
    url: https://run.mocky.io/v3/a193d0d8-7da4-45f5-ab77-b82196091138


#    datamock
#  {"resultA":{"id":"1234"},"resultB":{"id":"1234"},"resultC":{"id":"1234"},"id":"fbf59909-315d-4deb-b8e0-6ed0e8456c5b"}